presubmits:
  - name: pull-kcp-operator-verify
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.3-1
          command:
            - make
            - verify
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-kcp-operator-lint
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.3-1
          command:
            - make
            - lint
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-kcp-operator-build-image
    decorate: true
    run_if_changed: "(Dockerfile|Makefile|.prow.yaml|go.mod|go.sum|cmd|internal|sdk|hack)"
    optional: false
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/containers/buildah:v1.30.0
          command:
            - hack/ci/build-image.sh
          env:
            - name: DRY_RUN
              value: "1"
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-kcp-operator-test
    decorate: true
    run_if_changed: "(Dockerfile|Makefile|.prow.yaml|go.mod|go.sum|cmd|internal|sdk|hack|test)"
    optional: false
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.3-1
          command:
            - make
            - test
          env:
            - name: USE_GOTESTSUM
              value: "1"
          resources:
            requests:
              memory: 8Gi
              cpu: 4

  - name: pull-kcp-operator-test-e2e-0.28
    decorate: true
    run_if_changed: "(Dockerfile|Makefile|.prow.yaml|go.mod|go.sum|cmd|internal|sdk|hack|test|config)"
    optional: false
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.3-1
          command:
            - hack/ci/run-e2e-tests.sh
          env:
            - name: KCP_TAG
              value: release-0.28
          resources:
            requests:
              memory: 8Gi
              cpu: 4
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true

  - name: pull-kcp-operator-test-e2e-0.29
    decorate: true
    run_if_changed: "(Dockerfile|Makefile|.prow.yaml|go.mod|go.sum|cmd|internal|sdk|hack|test|config)"
    optional: false
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.3-1
          command:
            - hack/ci/run-e2e-tests.sh
          env:
            - name: KCP_TAG
              value: release-0.29
          resources:
            requests:
              memory: 8Gi
              cpu: 4
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true

  - name: pull-kcp-operator-test-e2e-0.30
    decorate: true
    run_if_changed: "(Dockerfile|Makefile|.prow.yaml|go.mod|go.sum|cmd|internal|sdk|hack|test|config)"
    optional: false
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.3-1
          command:
            - hack/ci/run-e2e-tests.sh
          env:
            - name: KCP_TAG
              value: release-0.30
          resources:
            requests:
              memory: 8Gi
              cpu: 4
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true

  # default is currently kcp 0.31
  - name: pull-kcp-operator-test-e2e-default
    decorate: true
    run_if_changed: "(Dockerfile|Makefile|.prow.yaml|go.mod|go.sum|cmd|internal|sdk|hack|test|config)"
    optional: false
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.3-1
          command:
            - hack/ci/run-e2e-tests.sh
          resources:
            requests:
              memory: 8Gi
              cpu: 4
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true

  - name: pull-kcp-operator-test-e2e-canary
    decorate: true
    run_if_changed: "(Dockerfile|Makefile|.prow.yaml|go.mod|go.sum|cmd|internal|sdk|hack|test|config)"
    optional: true
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.3-1
          command:
            - hack/ci/run-e2e-tests.sh
          env:
            - name: KCP_TAG
              value: main
            - name: KCP_RELEASE
              value: '0.32'
          resources:
            requests:
              memory: 8Gi
              cpu: 4
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true

  - name: pull-kcp-operator-test-kcp-e2e
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/kcp-operator"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.26.2-1
          command:
            - hack/ci/run-kcp-e2e-tests.sh
          resources:
            requests:
              memory: 4Gi
              cpu: 2
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
